### ISSUE TITLE
Add :clean command

### ISSUE THREAD

**Issue by NeonGraal** [NeonGraal/script-venv#19]
### Description

The ``:clean VENV`` command performs a ``--clean`` on the given venv and then re-applies any requirements. If the venv doesn't exists it will be created and have it's requirements applied.

### Usage

```
$ sv :clean venv
```

**Comment by crunchy234** [comment]
# Changes
```:clean VENV``` to be changed to ```:create VENV|SCRIPT``` where create will create the ```VENV```.
If the ```VENV``` exists ```:create``` will apply the requirements again.
When called with the ```--clean``` flag the given ```VENV``` will be cleaned and then requirements will be reapplied.

When passed a script the command will be executed on the venv to which that script belongs.

The venv will always take priority over the scripts venv.
