### ISSUE TITLE
Add an upgrade command

### ISSUE THREAD

**Issue by crunchy234** [NeonGraal/script-venv#24]
# Description
The ```:update VENV|SCRIPT``` command will upgrade pip and then all of the other requirements specified.

## Usage
The following will update the venvs requirements and its version of pip
```sh
$ sv :update venv
```
The following command will update the scripts venvs requirements and its version of pip
```sh
$ sh :update script
```

**Comment by NeonGraal** [comment]
This can be achieved by using the `:create` command with a `-U` extra parameter.

To upgrade `pip` as well just add `-U` `pip`
